project_masterdetails_crud/Controllers/DressesController.cs
using PagedList;
using project_masterdetails_crud.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace project_masterdetails_crud.Models.Controllers
{
    [Authorize]
    public class DressesController : Controller
    {
        private readonly StyleweekDbContext db = new StyleweekDbContext();
        // GET: Dresses
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public PartialViewResult DressDetails(int pg = 1)
        {
            var data = db.Dresses
                       .Include(x=>x.Stocks)
                       .Include(x => x.DressModel)
                       .Include(x => x.Brand)
                       .OrderBy(x => x.DressId)
                       .ToPagedList(pg, 5);
            return PartialView("_DressDetails", data);
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult CreateForm()
        {
            DressInputModel model = new DressInputModel();
            model.Stocks.Add(new Stock());
            ViewBag.DressModels = db.DressModels.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return PartialView("_CreateForm", model);
        }
        [HttpPost]
        public ActionResult Create(DressInputModel model, string act = "")
        {
            if (act == "add")
            {
                model.Stocks.Add(new Stock());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.Stocks.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act == "insert")
            {
                if (ModelState.IsValid)
                {
                    var dress = new Dress
                    {
                        BrandId = model.BrandId,
                        DressModelId = model.DressModelId,
                        Name = model.Name,
                        FirstIntroduceOn = model.FirstIntroduceOn,
                        OnSale = model.OnSale
                    };
                    //For Image
                    string ext = Path.GetExtension(model.Picture.FileName);
                    string f = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Path.Combine(Server.MapPath("~/Images"), f);
                    model.Picture.SaveAs(savePath);
                    dress.Picture = f;

                    db.Dresses.Add(dress);
                    db.SaveChanges();

                    //Stocks
                    foreach (var s in model.Stocks)
                    {
                        db.Database.ExecuteSqlCommand($"spInsertStock {(int)s.Size},{s.Price},{(int)s.Quantity},{dress.DressId}");
                    }

                    DressInputModel newModel = new DressInputModel()
                    {
                        Name = "",
                        FirstIntroduceOn = DateTime.Today
                    };
                    newModel.Stocks.Add(new Stock());

                    ViewBag.DressModels = db.DressModels.ToList();
                    ViewBag.Brands = db.Brands.ToList();
                    foreach (var e in ModelState.Values)
                    {
                        e.Value = null;
                    }
                    return View("_CreateForm", newModel);
                }
            }
            ViewBag.DressModels = db.DressModels.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return View("_CreateForm", model);
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public ActionResult EditForm(int id)
        {
            var data = db.Dresses.FirstOrDefault(x => x.DressId == id);
            if (data == null) return new HttpNotFoundResult();
            db.Entry(data).Collection(x => x.Stocks).Load();
            DressEditModel model = new DressEditModel
            {
                DressId = id,
                BrandId = data.BrandId,
                DressModelId = data.DressModelId,
                Name = data.Name,
                FirstIntroduceOn = data.FirstIntroduceOn,
                OnSale = data.OnSale,
                Stocks = data.Stocks.ToList()
            };
            ViewBag.DressModels = db.DressModels.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.CurrentPic = data.Picture;
            return PartialView("_EditForm", model);
        }
        [HttpPost]
        public ActionResult Edit(DressEditModel model, string act = "")
        {
            if (act == "add")
            {
                model.Stocks.Add(new Stock());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.Stocks.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act == "update")
            {
                if (ModelState.IsValid)
                {
                    var dress = db.Dresses.FirstOrDefault(x => x.DressId == model.DressId);
                    if (dress == null) { return new HttpNotFoundResult(); }
                    dress.Name = model.Name;
                    dress.FirstIntroduceOn = model.FirstIntroduceOn;
                    dress.OnSale = model.OnSale;
                    dress.BrandId = model.BrandId;
                    dress.DressModelId = model.DressModelId;
                    if (model.Picture != null)
                    {
                        string ext = Path.GetExtension(model.Picture.FileName);
                        string f = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string savePath = Path.Combine(Server.MapPath("~/Images"), f);
                        model.Picture.SaveAs(savePath);
                        dress.Picture = f;
                    }
                    else
                    {

                    }

                    db.SaveChanges();                   
                    db.Database.ExecuteSqlCommand($"EXEC DeleteStockByDressId {dress.DressId}");
                    foreach (var s in model.Stocks)
                    {
                        db.Database.ExecuteSqlCommand($"EXEC spInsertStock {(int)s.Size}, {s.Price}, {s.Quantity}, {dress.DressId}");
                    }
                    return RedirectToAction("Index");
                }
            }
            ViewBag.DressModels = db.DressModels.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.CurrentPic = db.Dresses.FirstOrDefault(x => x.DressId == model.DressId)?.Picture;
            return View("_EditForm", model);
        }
        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                var drs = db.Dresses .FirstOrDefault(x => x.DressId == id);
                var dressDetails = db.Dresses.FirstOrDefault(x => x.DressId == id);

                db.Dresses.Remove(dressDetails);
                db.Dresses.Remove(drs);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Index");
        }
    }
}

project_masterdetails_crud/Views/Dresses/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col">
        <div id="form-div">
            @Html.Action("CreateForm")
        </div>
    </div>
</div>
<div>
    <a href="@Url.Action("Index","Dresses")" class="btn btn-link btn-sm"><i class="fa fa-arrow-circle-left"></i> Back to list</a>
</div>

project_masterdetails_crud/Views/Dresses/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
<div class="row">
    <div class="col">
        <div id="form-div">
            @Html.Action("EditForm")
        </div>
    </div>
</div>

project_masterdetails_crud/Views/Dresses/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 class="display-4 form-text">Dress List</h2>
<div class="card mb-2"style="background-image: url('../../images/card2.jpg'); ">
    <div class="card-body">
        <div class="row">
            <div class="col">
                <div class="d-flex justify-content-end">
                    <a href="@Url.Action("Create","Dresses")" class="btn btn-outline-primary btn-sm"><i class="fa fa-plus-circle"></i> Add New Dress</a>
                </div>
                <div id="table-div">
                    @Html.Action("DressDetails")
                </div>
            </div>
        </div>
        @section styles{

            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
        }
        @section scripts{
            <script src="~/Scripts/jquery-3.7.1.js"></script>
            <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

            <script>
                $(document).on("click", "button.show", function () {
                    var showBtn = $(this);
                    var hideBtn = showBtn.next();
                    var trSh = showBtn.closest("tr");
                    var trSt = trSh.next();
                    showBtn.hide();
                    hideBtn.show();
                    trSt.show();
                });
                $(document).on("click", "button.hide", function () {
                    var hideBtn = $(this);
                    var showBtn = hideBtn.prev();
                    var trSh = showBtn.closest("tr");
                    var trSt = trSh.next();
                    showBtn.show();
                    hideBtn.hide();
                    trSt.hide();
                });
            </script>
        </div>
 </div>
    }

project_masterdetails_crud/Views/Dresses/_CreateForm.cshtml
@model project_masterdetails_crud.Models.ViewModels.DressInputModel

@using (Ajax.BeginForm("Create", "Dresses", new { }, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "form-div",
    OnSuccess = "OnSuccess"
}, new { id = "frm", enctype = "multipart/form-data" }))
{

    <div class="row" style="background-image: url('../../images/card5.jpg'); ">
        <div class="col-6">
            <h2 class="display-5">Add New Dress</h2>
            <div class="row mb-2">
                @Html.LabelFor(x => x.BrandId, new { @class = "col-form-label col-2" })
                <div class="col-6">
                    @Html.DropDownListFor(x => x.BrandId, new SelectList(ViewBag.Brands, "BrandId", "BrandName"), "---Select---", new { @class = "form-select" })
                </div>
                <div class="col-4">
                    @Html.ValidationMessageFor(x => x.BrandId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.DressModelId, new { @class = "col-form-label col-2" })
                <div class="col-6">
                    @Html.DropDownListFor(x => x.DressModelId, new SelectList(ViewBag.DressModels, "DressModelId", "ModelName"), "---Select---", new { @class = "form-select" })
                </div>
                <div class="col-4">
                    @Html.ValidationMessageFor(x => x.DressModelId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.Name, new { @class = "col-form-label col-2" })
                <div class="col-6">
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                </div>
                <div class="col-4">
                    @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.FirstIntroduceOn, new { @class = "col-form-label col-2" })
                <div class="col-6">
                    @Html.TextBoxFor(x => x.FirstIntroduceOn, new { @class = "form-control", type = "date", @value = DateTime.Today.ToString("yyyy-MM-dd") })
                </div>
                <div class="col-4">
                    @Html.ValidationMessageFor(x => x.FirstIntroduceOn, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2" })
                <div class="col-6">
                    @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
                </div>
                <div class="col-4">
                    @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-10 offset-2">
                    <div class="form-check">
                        @Html.CheckBoxFor(x => x.OnSale)
                        <label>
                            On Sale?
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="row mb-">
                <div class="col-6">
                    <div class="d-flex justify-content-between">
                        <h2 class="display-5">Stocks</h2>
                        
                    </div>
                    <div class="d-flex justify-content-end mb-3">
                        <button class="btn btn-outline-primary btn-sm" type="submit" name="act" value="add" formnovalidate><i class="fa fa-plus-circle"></i></button>
                    </div>
                    <table class="table table-bordered table-sm">
                        <thead>
                            <tr>
                                <th>Size</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.Stocks.Count; i++)
                            {
                                <tr>
                                    <td>
                                        @Html.EnumDropDownListFor(x => Model.Stocks[i].Size, new { @class = "form-select" })
                                        @Html.ValidationMessageFor(x => Model.Stocks[i].Size, "", new { @class = "text-danger" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(x => Model.Stocks[i].Price, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(x => Model.Stocks[i].Price, "", new { @class = "text-danger" })
                                    </td>
                                    <td>
                                        @Html.TextBoxFor(x => Model.Stocks[i].Quantity, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(x => Model.Stocks[i].Quantity, "", new { @class = "text-danger" })
                                    </td>
                                    <td>
                                        <button name="act" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate><i class="fa fa-trash"></i></button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-center">
                        <button type="submit" name="act" value="insert" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

project_masterdetails_crud/Views/Dresses/_DressDetails.cshtml
@model IEnumerable<project_masterdetails_crud.Models.Dress>
@using PagedList
@using PagedList.Mvc

<table class="table table-bordered table-striped table-sm mt-2">
    <thead class="table-primary">
        <tr>
            <th></th>
            <th></th>
            <th>Brand</th>
            <th>Model</th>
            <th>First Introduced</th>
            <th>On Sale?</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td style="width:40px;text-align:center;">
                    <button type="button" class="btn btn-sm show"><i class="bi bi-chevron-right"></i></button>
                    <button type="button" class="btn btn-sm hide" style="display:none;"><i class="bi bi-chevron-up"></i></button>
                </td>
                <td style="width:45px;text-align:center">
                    <img src="~/Images/@s.Picture" class="rounded-circle" style="width:32px;" />
                </td>
                <td>@s.Brand.BrandName</td>
                <td>@s.DressModel.ModelName</td>
                <td>@s.FirstIntroduceOn.ToString("yyyy-MM-dd")</td>
                <td>@(s.OnSale?"Yes":"No")</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Dresses", new { id = s.DressId }, new { @class = "btn btn-outline-success btn-sm" })
                    @Html.ActionLink("Delete", "Delete", "Dresses", new { id = s.DressId }, new { @class = "btn btn-outline-danger btn-sm" })
                </td>
            </tr>
            <tr style="display:none;">
                <td></td>
                <td colspan="6">
                    <h4>Stocks</h4>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Size</th>
                                <th>Price</th>
                                <th>Quantity</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var t in s.Stocks)
                            {
                                <tr>
                                    <td>@t.Size</td>
                                    <td>@t.Price</td>
                                    <td>@t.Quantity</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
            </tr>
        }
    </tbody>
</table>

project_masterdetails_crud/Views/Dresses/_EditForm.cshtml
@model project_masterdetails_crud.Models.ViewModels.DressEditModel

@using (Ajax.BeginForm("Edit", "Dresses", new { }, new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "form-div"
}, new { id = "frm", enctype = "multipart/form-data" }))
{
    <div class="row" style="background-image: url('../../images/card2.jpg'); ">


        <h2 class="display-4">Edit Dress</h2>
        <div class="row mb-2">
            @Html.HiddenFor(x => x.DressId)
            @Html.HiddenFor(x => x.Picture)
            @Html.LabelFor(x => x.BrandId, new { @class = "col-form-label col-2 " })
            <div class="col-6">
                @Html.DropDownListFor(x => x.BrandId, new SelectList(ViewBag.Brands, "BrandId", "BrandName"), "---Select---", new { @class = "form-select" })
            </div>
            <div class="col-4">
                @Html.ValidationMessageFor(x => x.BrandId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row mb-2">
            @Html.LabelFor(x => x.DressModelId, new { @class = "col-form-label col-2 " })
            <div class="col-6">
                @Html.DropDownListFor(x => x.DressModelId, new SelectList(ViewBag.DressModels, "DressModelId", "ModelName"), "---Select---", new { @class = "form-select" })
            </div>
            <div class="col-4">
                @Html.ValidationMessageFor(x => x.DressModelId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row mb-2">
            @Html.LabelFor(x => x.Name, new { @class = "col-form-label col-2 " })
            <div class="col-6">
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            </div>
            <div class="col-4">
                @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row mb-2">
            @Html.LabelFor(x => x.FirstIntroduceOn, new { @class = "col-form-label col-2 " })
            <div class="col-6">
                @Html.EditorFor(x => x.FirstIntroduceOn, "{0:yyyy-MM-dd}", new { htmlAttributes = new { @class = "form-control", type = "date" } })
            </div>
            <div class="col-4">
                @Html.ValidationMessageFor(x => x.FirstIntroduceOn, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row mb-2">
            @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2 " })
            <div class="col-6">
                @Html.TextBoxFor(x => x.Picture, new { @class = "form-control mb-1", @type = "file" })
                <img src="~/Images/@ViewBag.CurrentPic" style="width:35px;" class="img-thumbnail" />
            </div>
            <div class="col-4">
                @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-10 offset-2">
                <div class="form-check">
                    @Html.CheckBoxFor(x => x.OnSale)
                    <label>
                        On Sale?
                    </label>
                </div>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-6">
                <div class="d-flex justify-content-between">
                    <h3>Stocks</h3>
                    <button class="btn btn-outline-primary btn-sm" type="submit" name="act" value="add" formnovalidate><i class="fa fa-plus-circle"></i></button>
                </div>
                <table class="table table-bordered table-sm">
                    <thead>
                        <tr>
                            <th>Size</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (var i = 0; i < Model.Stocks.Count; i++)
                        {
                            <tr>
                                <td>
                                    @Html.EnumDropDownListFor(x => Model.Stocks[i].Size, new { @class = "form-select" })
                                    @Html.ValidationMessageFor(x => Model.Stocks[i].Size, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    @Html.TextBoxFor(x => Model.Stocks[i].Price, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => Model.Stocks[i].Price, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    @Html.TextBoxFor(x => Model.Stocks[i].Quantity, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => Model.Stocks[i].Quantity, "", new { @class = "text-danger" })
                                </td>
                                <td>
                                    <button name="act" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate><i class="fa fa-trash"></i></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-6">
                <button type="submit" name="act" value="update" class="btn btn-primary">Update</button>
            </div>
        </div>
    </div>
}
<div>
    <a href="@Url.Action("Index","Dresses")" class="btn btn-link btn-sm"><i class="fa fa-arrow-circle-left"></i> Back to list</a>
</div>