project_masterdetails_crud/Controllers/DressModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace project_masterdetails_crud.Models.Controllers
{
    public class DressModelsController : Controller
    {
        private StyleweekDbContext db = new StyleweekDbContext();
        public ActionResult Index()
        {
            return View(db.DressModels.ToList());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DressModel dressModel = db.DressModels.Find(id);
            if (dressModel == null)
            {
                return HttpNotFound();
            }
            return View(dressModel);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DressModelId,ModelName")] DressModel dressModel)
        {
            if (ModelState.IsValid)
            {
                db.DressModels.Add(dressModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dressModel);
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DressModel dressModel = db.DressModels.Find(id);
            if (dressModel == null)
            {
                return HttpNotFound();
            }
            return View(dressModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DressModelId,ModelName")] DressModel dressModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dressModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dressModel);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DressModel dressModel = db.DressModels.Find(id);
            if (dressModel == null)
            {
                return HttpNotFound();
            }
            return View(dressModel);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DressModel dressModel = db.DressModels.Find(id);
            db.DressModels.Remove(dressModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

project_masterdetails_crud/Views/DressModels/Create.cshtml
@model project_masterdetails_crud.Models.DressModel

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="card">
        <div class="card-body" style="background-image: url('../../images/card2.jpg');">
            <div class="col">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.ModelName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ModelName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ModelName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-outline-info" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

project_masterdetails_crud/Views/DressModels/Delete.cshtml
@model project_masterdetails_crud.Models.DressModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DressModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ModelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModelName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

project_masterdetails_crud/Views/DressModels/Edit.cshtml
@model project_masterdetails_crud.Models.DressModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DressModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DressModelId)

        <div class="form-group">
            @Html.LabelFor(model => model.ModelName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModelName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModelName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

project_masterdetails_crud/Views/DressModels/Index.cshtml
@model IEnumerable<project_masterdetails_crud.Models.DressModel>

@{
    ViewBag.Title = "Dress Model";
}
<div class="card">
    <div class="card-body" style="background-image: url('../../images/card2.jpg');">
        <div class="row">
            <div class="col">
                <p class="d-flex justify-content-end">
                    <a href="@Url.Action("Create","DressModels")" class="btn btn-outline-primary">Add New</a>
                </p>
                <table class="table table-bordered table-striped table-sm table-hover">
                    <thead class="table-info">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.ModelName)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ModelName)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.DressModelId }, new { @class = "btn btn-outline-info btn-sm" })
                                    @Html.ActionLink("Delete", "Delete", new { id = item.DressModelId }, new { @class = "btn btn-outline-danger btn-sm" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>